receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  # Export to Tempo
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Export to Loki
  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  # Export to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "alicenbob"
    const_labels:
      label1: value1
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

processors:
  batch:

  redaction:
    allow_all_keys: true
    blocked_key_patterns:
      - ".*token.*"
      - ".*api_key.*"
    hash_function: md5

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]

    logs:
      receivers: [otlp]
      processors: [batch, redaction]
      exporters: [otlphttp/loki, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
