receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  # Export to Tempo
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Export to Loki
  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

processors:
  batch:

  redaction:
    allow_all_keys: true
    blocked_key_patterns:
      - ".*token.*"
      - ".*api_key.*"
    hash_function: md5

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]

    logs:
      receivers: [otlp]
      processors: [batch, redaction]
      exporters: [otlphttp/loki, debug]
